version: '2'

services:
  lovebot:
    container_name: lovebot
    build:
      context: ./
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - ./:/opt/app
      - /opt/app/node_modules
      - /opt/app/db
    environment:
      SLACK_TOKEN: insert-token-here
      DB_LOCATION: /opt/app/db/lovebot.db
